name: Deployment
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3.5.0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0
        with:
          gradle-home-cache-cleanup: true
      - name: Configure Gradle properties
        run: |
          touch $FILE
          echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" >> $FILE
          echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >> $FILE
        env:
          FILE: ~/.gradle/gradle.properties
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: Publish to Gradle Plugin Portal
        run: ./gradlew :jvm:publishPlugins
        env:
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Clean Gradle properties
        run: rm ~/.gradle/gradle.properties
